### ISSUE TITLE
Drop all binary wheels.

### ISSUE THREAD

**Issue by dumol** [chevah/pythia#55]
From https://github.com/chevah/server/pull/6613:
```
The imporant part is to build the next version of Pythia without binary wheels.
We can have those wheels installed in chevah/server.
```

One this is implemented, we should use it in chevah/server and do some cleanup as right now in chevah/server we have a few workarounds https://github.com/chevah/server/issues/6639

**Comment by adiroiban** [comment]
I think that we can skip Pytho 3.12 and look at Python 3.13 as the next update.

3.13 is still alpha ... and not very stable. Scheduled for September 2024

But once the beta is out, we can try to build Pythia.

We can continue to use 3.11 for some time, but I prefer to try to keep using the latest Python

In this way, when we upgrade from one version to another, the changes are not big.

We will do upgrades more often, with fewer changes between versions... rather than fewer upgrades with more changes between versions.

**Comment by dumol** [comment]
Removed through https://github.com/chevah/pythia/pull/58/files/87713dd07663bd54356c8ea397cc8167d82a8560..8aaeaa3a9328d8d71e91f618f21fa31303d3fd80.
